### ISSUE TITLE
Error step 1 calibration.

### ISSUE THREAD

**Issue by DemOnJR** [Freenove/Freenove_Quadruped_Robot_Kit#2]
I recive this error:
WIFI
21:17:42 Client connection start: connect to port...
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at processing.net.Client.<init>(Unknown Source)
	at Processing$Communication.StartClient(Processing.java:834)
	at Processing.processEvent(Processing.java:594)
	at Processing.processEvent(Processing.java:98)
	at Processing.draw(Processing.java:93)
	at processing.core.PApplet.handleDraw(PApplet.java:2426)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
21:17:43 Client connection failed

**Comment by DemOnJR** [comment]
WIFI
21:19:49 Client connection start: connect to port...
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at processing.net.Client.<init>(Unknown Source)
	at Processing$Communication.StartClient(Processing.java:834)
	at Processing.processEvent(Processing.java:594)
	at Processing.processEvent(Processing.java:98)
	at Processing.draw(Processing.java:93)
	at processing.core.PApplet.handleDraw(PApplet.java:2426)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
21:20:10 Client connection failed

**Comment by DemOnJR** [comment]
SERIAL
21:21:27 Serial connection start: detecte serial...
21:21:27 Serial detected: COM4 
21:21:27 Serial connection attempt: COM4...
21:21:29 Serial read failed: time out
21:21:29 Serial connection failed: detected serial, no serial responded

**Comment by DemOnJR** [comment]
Solved.
